const { exec } = require('child_process');
const { promisify } = require('util');
const fs = require('fs').promises;
const path = require('path');
const axios = require('axios');
const execAsync = promisify(exec);
const gh = require('../services/github');

const TOOLS = {
  bash: async ({ command, cwd }) => {
    const { stdout, stderr } = await execAsync(command, {
      cwd: cwd || process.env.WORKSPACE || '/tmp',
      timeout: 30000,
      env: { ...process.env }
    });
    return (stdout + stderr).slice(0, 3000);
  },

  read_file: async ({ path: p }) => {
    const content = await fs.readFile(p, 'utf8');
    return content.slice(0, 5000);
  },

  write_file: async ({ path: p, content }) => {
    await fs.mkdir(path.dirname(p), { recursive: true });
    await fs.writeFile(p, content);
    return `Written: ${p}`;
  },

  list_files: async ({ path: p }) => {
    const items = await fs.readdir(p || '.', { withFileTypes: true });
    return items.map(i => `${i.isDirectory() ? 'd' : 'f'} ${i.name}`).join('\n');
  },

  web_search: async ({ query }) => {
    // Use DuckDuckGo HTML scraping as fallback
    const r = await axios.get(`https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_redirect=1`);
    const data = r.data;
    const results = [data.Abstract, ...(data.RelatedTopics || []).slice(0, 5).map(t => t.Text)].filter(Boolean);
    return results.join('\n\n').slice(0, 3000);
  },

  github_get_issue: async ({ owner, repo, issue_number }, ctx) => {
    const o = owner || ctx?.repoOwner;
    const r = repo || ctx?.repoName;
    const issue = await gh.getIssue(o, r, parseInt(issue_number));
    return JSON.stringify({ title: issue.title, body: issue.body, state: issue.state, comments: issue.comments.slice(0, 3).map(c => c.body) }, null, 2);
  },

  github_list_issues: async ({ owner, repo, state }, ctx) => {
    const issues = await gh.listIssues(owner || ctx?.repoOwner, repo || ctx?.repoName, state || 'open');
    return issues.map(i => `#${i.number}: ${i.title} [${i.state}]`).join('\n');
  },

  github_comment: async ({ owner, repo, issue_number, body }, ctx) => {
    const result = await gh.createIssueComment(owner || ctx?.repoOwner, repo || ctx?.repoName, parseInt(issue_number), body);
    return `Comment posted: ${result.html_url}`;
  },

  github_close_issue: async ({ owner, repo, issue_number, comment }, ctx) => {
    await gh.closeIssue(owner || ctx?.repoOwner, repo || ctx?.repoName, parseInt(issue_number), comment);
    return `Issue #${issue_number} closed`;
  },

  github_get_file: async ({ owner, repo, path: p }, ctx) => {
    const content = await gh.getFileContent(owner || ctx?.repoOwner, repo || ctx?.repoName, p);
    return content.slice(0, 5000);
  },

  github_list_files: async ({ owner, repo, path: p }, ctx) => {
    const items = await gh.getRepoContents(owner || ctx?.repoOwner, repo || ctx?.repoName, p || '');
    if (Array.isArray(items)) return items.map(i => `${i.type} ${i.path}`).join('\n');
    return JSON.stringify(items);
  },

  github_create_pr: async ({ owner, repo, title, body, head, base }, ctx) => {
    const pr = await gh.createPR(owner || ctx?.repoOwner, repo || ctx?.repoName, title, body, head, base);
    return `PR created: ${pr.html_url}`;
  },

  analyze_code: async ({ code, language, task }) => {
    // Just return structured analysis request - will be handled by the model itself
    return `Analyzing ${language || 'code'} for: ${task}\n${code.slice(0, 2000)}`;
  },

  create_plan: async ({ task, context }) => {
    return `Planning task: ${task}\nContext: ${context || 'none'}\nPlan will be generated by the model.`;
  }
};

function getToolDefs() {
  return [
    { type: 'function', function: { name: 'bash', description: 'Run bash commands', parameters: { type: 'object', properties: { command: { type: 'string' }, cwd: { type: 'string' } }, required: ['command'] } } },
    { type: 'function', function: { name: 'read_file', description: 'Read a file', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } } },
    { type: 'function', function: { name: 'write_file', description: 'Write content to file', parameters: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } } },
    { type: 'function', function: { name: 'list_files', description: 'List files in directory', parameters: { type: 'object', properties: { path: { type: 'string' } } } } },
    { type: 'function', function: { name: 'web_search', description: 'Search the web for information', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
    { type: 'function', function: { name: 'github_get_issue', description: 'Get a GitHub issue with comments', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, issue_number: { type: 'number' } }, required: ['issue_number'] } } },
    { type: 'function', function: { name: 'github_list_issues', description: 'List GitHub issues', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, state: { type: 'string' } } } } },
    { type: 'function', function: { name: 'github_comment', description: 'Post comment on GitHub issue', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, issue_number: { type: 'number' }, body: { type: 'string' } }, required: ['issue_number', 'body'] } } },
    { type: 'function', function: { name: 'github_close_issue', description: 'Close a GitHub issue', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, issue_number: { type: 'number' }, comment: { type: 'string' } }, required: ['issue_number'] } } },
    { type: 'function', function: { name: 'github_get_file', description: 'Get file content from GitHub repo', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, path: { type: 'string' } }, required: ['path'] } } },
    { type: 'function', function: { name: 'github_list_files', description: 'List files in GitHub repo', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, path: { type: 'string' } } } } },
    { type: 'function', function: { name: 'github_create_pr', description: 'Create a Pull Request', parameters: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, title: { type: 'string' }, body: { type: 'string' }, head: { type: 'string' }, base: { type: 'string' } }, required: ['title', 'body', 'head'] } } },
    { type: 'function', function: { name: 'analyze_code', description: 'Analyze code for bugs, improvements, security issues', parameters: { type: 'object', properties: { code: { type: 'string' }, language: { type: 'string' }, task: { type: 'string' } }, required: ['code'] } } },
    { type: 'function', function: { name: 'create_plan', description: 'Create a detailed plan for a task', parameters: { type: 'object', properties: { task: { type: 'string' }, context: { type: 'string' } }, required: ['task'] } } }
  ];
}

async function execute(name, args, ctx) {
  if (!TOOLS[name]) throw new Error(`Unknown tool: ${name}`);
  return await TOOLS[name](args, ctx);
}

module.exports = { execute, getToolDefs };
